--- 
abstract: ~
author: Elliot Shank <perl@galumph.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Perl-Critic-IncludingOptionalDepencencies
no_index: 
  directory: 
    - inc
    - t
requires: 
  File::HomeDir: 0
  File::Which: 0
  IO::String: 1
  IPC::Open2: 1
  Perl::MinimumVersion: 0
  Perl::Tidy: 0
  Pod::Spell: 1
  Task::Perl::Critic: 1.002
  Term::ANSIColor: 0
  Text::ParseWords: 3
  perl: 5.6.1
version: v1.000
